name: tflint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]      

  schedule:
    - cron: '25 13 * * 6'
  
  
jobs:
  tflint-check:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        tflint_version: v0.40.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint 
  

